{% set name = "sxscatalog" %}
{% set version = "3.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sxscatalog-{{ version }}.tar.gz
  sha256: d9c7a19c45a87df4be40d4f634a3503f08ddfc6b09c5a1d774205bf377e4cf3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - pandas
    - numpy
    - packaging

test:
  imports:
    - sxscatalog
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sxs-collaboration/sxscatalog
  summary: Interface to the catalog of SXS simulations
  dev_url: https://github.com/sxs-collaboration/sxscatalog
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - moble
