{% set name = "sxscatalog" %}
{% set version = "3.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sxscatalog-{{ version }}.tar.gz
  sha256: be8da2959408fdece411b0ce58f54e3029282309eab8a5b1b315bcef03460025

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - pandas
    - numpy
    - packaging

test:
  imports:
    - sxscatalog
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sxs-collaboration/sxscatalog
  summary: Interface to the catalog of SXS simulations
  dev_url: https://github.com/sxs-collaboration/sxscatalog
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - moble
