{% set name = "sxscatalog" %}
{% set version = "3.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sxscatalog-{{ version }}.tar.gz
  sha256: 13a985ffa019d80cc5ec53a77a2c4b4fbecc47caacbc922f63087ebba4a20415

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - pandas
    - numpy
    - packaging

test:
  imports:
    - sxscatalog
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sxs-collaboration/sxscatalog
  summary: Interface to the catalog of SXS simulations
  dev_url: https://github.com/sxs-collaboration/sxscatalog
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - moble
